In [44]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [45]:
# Scrape DK Metcalf's receiving stats from Pro Football Reference
df = pd.read_csv('sportsref_download.csv')

In [46]:
df.head()

,Year,Age,Tm,Pos,No.,G,GS,Tgt,Rec,Yds,Y/R,TD,1D,Lng,R/G,Y/G,Ctch%,Y/Tgt
0,2019,22,SEA,WR,14,16,15,100,58,900,15.5,7,39,54,3.6,56.3,58.00%,9.0
1,2020,23,SEA,WR,14,16,16,129,83,1303,15.7,10,63,62,5.2,81.4,64.30%,10.1
2,2021,24,SEA,WR,14,17,17,129,75,967,12.9,12,48,84,4.4,56.9,58.10%,7.5
3,2022,25,SEA,WR,14,17,17,141,90,1048,11.6,6,47,54,5.3,61.6,63.80%,7.4

Clean the data

In [47]:
# Clean the data
df = df.dropna()
df = df.rename(columns={"G":"Games", "Tgt":"Targets", "Rec":"Receptions", "Yds":"Receiving_Yards", "Y/Tgt":"Yards_per_Target", "Y/G":"Yards_per_Game"})

In [48]:
df.head()

,Year,Age,Tm,Pos,No.,Games,GS,Targets,Receptions,Receiving_Yards,Y/R,TD,1D,Lng,R/G,Yards_per_Game,Ctch%,Yards_per_Target
0,2019,22,SEA,WR,14,16,15,100,58,900,15.5,7,39,54,3.6,56.3,58.00%,9.0
1,2020,23,SEA,WR,14,16,16,129,83,1303,15.7,10,63,62,5.2,81.4,64.30%,10.1
2,2021,24,SEA,WR,14,17,17,129,75,967,12.9,12,48,84,4.4,56.9,58.10%,7.5
3,2022,25,SEA,WR,14,17,17,141,90,1048,11.6,6,47,54,5.3,61.6,63.80%,7.4

In [49]:
# Choose features
features = ["Age", "Games", "Receptions", "Targets", "Yards_per_Target", "Yards_per_Game"]

In [50]:
# Train a linear regression model
model = LinearRegression()
model.fit(df[features], df["Receiving_Yards"])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [51]:
# Make a prediction for the upcoming season
age = 26
games = 17
receptions = 85
targets = 120
yards_per_target = 7.9
yards_per_game = 71.5

receiving_yards_prediction = model.predict([[age, games, receptions, targets, yards_per_target, yards_per_game]])[0]

In [52]:
# Print the prediction
print(f"DK Metcalf's projected receiving yards for the upcoming season is {receiving_yards_prediction:,}")

DK Metcalf's projected receiving yards for the upcoming season is 1,132.0270026764586